<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="limo_ackerman">

    <xacro:arg name="robot_namespace" default="/" />
    <xacro:include filename="$(find limo_description)/urdf/limo_xacro.xacro" />
    <!-- <xacro:include filename="$(find limo_description)/urdf/limo_steering_hinge.xacro" /> -->
    <!-- <xacro:include filename="$(find limo_description)/urdf/limo_ackerman.gazebo" /> -->
    <xacro:include filename="$(find limo_description)/urdf/gazebo_control.xacro" />
    <xacro:include filename="$(find limo_description)/urdf/inertial_macros.xacro" />
    <!-- <xacro:include filename="$(find limo_description)/urdf/limo_imu.xacro" /> -->

    <!-- Variables -->
    <xacro:property name="M_PI" value="3.14159265359"/>

    <!-- Vehicle Geometries -->
    <xacro:property name="base_x_size" value="0.2" />
    <xacro:property name="base_y_size" value="0.13" />
    <xacro:property name="base_z_size" value="0.1" />

    <xacro:property name="wheelbase" value="0.2"/>
    <xacro:property name="track" value="0.14"/>
    <xacro:property name="base_mass" value="3.0"/>
    <xacro:property name="wheel_vertical_offset" value="0.0" />
    <xacro:property name="wheel_length" value="0.045" />
    <xacro:property name="wheel_radius" value="0.045" />

    <!-- BASE FOOTPRINT -->

    <link name="base_footprint"/>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0.0 0.0 0.045" rpy="0 0 0"/>
    </joint>

    <!-- BASE LINK -->


    <link name="base_link">
        <xacro:inertial_box mass="3" x="${base_x_size}" y="${base_y_size}" z="${base_z_size}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
        <visual>
            <!-- <origin xyz="0 0 -0.045" rpy="0 0 ${pi/2}" /> -->
            <origin xyz="${wheelbase/2} 0 -0.045" rpy="0 0 ${pi/2}" />
            <geometry>
                <mesh filename="file:///$(find limo_description)/meshes/limo_base.dae" />
            </geometry>
        </visual>
        <collision>
            <!-- <origin xyz="0 0 -0.045" rpy="0 0 ${pi/2}" /> -->
            <!-- <origin xyz="0 0 0.045" rpy="0 0 0" /> -->
            <origin xyz="${wheelbase/2} 0 0.045" rpy="0 0 0" />
          <geometry>
              <box size="0.13 0.09 ${base_z_size}"/>
              <!-- <mesh filename="file:///$(find limo_description)/meshes/limo_base.dae" /> -->
          </geometry>
        </collision>
    </link>

    <!-- SENSOR -->

    <xacro:limo_laser parent_prefix="base_link" frame_prefix="laser">
        <origin xyz="${0.103+wheelbase/2} 0 ${-0.034+0.15-0.045}" rpy="0 0 0"/>
    </xacro:limo_laser>

    <xacro:limo_depth_camera parent_prefix="base_link" frame_prefix="depth_camera">
        <origin xyz="${0.084+wheelbase/2} 0 ${0.03+0.15-0.045}" rpy="0 0 0"/>
    </xacro:limo_depth_camera>

    <xacro:limo_imu parent_prefix="base_link" frame_prefix="imu">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:limo_imu>

    <!-- WHEEL LINK -->

    <link name="rear_right_wheel_link">
        <xacro:inertial_cylinder mass="0.1" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 ${-wheel_length/2}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
        <visual>
            <origin xyz="0 0 0" rpy="${-pi/2} 0 0" />
            <geometry>
                <mesh filename="file:///$(find limo_description)/meshes/limo_wheel.dae" />
            </geometry>
        </visual>
        <collision>
            <!-- <origin xyz="0 0 0" rpy="${-pi/2} 0 0" /> -->
            <origin xyz="0 0 ${-wheel_length/2}" rpy="0 0 0" />
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />
                <!-- <mesh filename="file:///$(find limo_description)/meshes/limo_wheel.dae" /> -->
            </geometry>
        </collision>
    </link>

    <link name="rear_left_wheel_link">
        <xacro:inertial_cylinder mass="0.1" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 ${wheel_length/2}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
        <visual>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
            <geometry>
                <mesh filename="file:///$(find limo_description)/meshes/limo_wheel.dae" />
            </geometry>
        </visual>
        <collision>
            <!-- <origin xyz="0 0 0" rpy="${pi/2} 0 0" /> -->
            <origin xyz="0 0 ${wheel_length/2}" rpy="0 0 0" />
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />
                <!-- <mesh filename="file:///$(find limo_description)/meshes/limo_wheel.dae" /> -->
            </geometry>
        </collision>
    </link>

    <link name="front_right_wheel_link">
        <xacro:inertial_cylinder mass="0.1" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 ${-wheel_length/2}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
        <visual>
            <origin xyz="0 0 0" rpy="${-pi/2} 0 0" />
            <geometry>
                <mesh filename="file:///$(find limo_description)/meshes/limo_wheel.dae" />
            </geometry>
        </visual>
        <collision>
            <!-- <origin xyz="0 0 0" rpy="${-pi/2} 0 0" /> -->
            <origin xyz="0 0 ${-wheel_length/2}" rpy="0 0 0" />
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />
                <!-- <mesh filename="file:///$(find limo_description)/meshes/limo_wheel.dae" /> -->
            </geometry>
        </collision>
    </link>

    <link name="front_left_wheel_link">
        <xacro:inertial_cylinder mass="0.1" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 ${wheel_length/2}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
        <visual>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
            <geometry>
                <mesh filename="file:///$(find limo_description)/meshes/limo_wheel.dae" />
            </geometry>
        </visual>
        <collision>
            <!-- <origin xyz="0 0 0" rpy="${pi/2} 0 0" /> -->
            <origin xyz="0 0 ${wheel_length/2}" rpy="0 0 0" />
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />
                <!-- <mesh filename="file:///$(find limo_description)/meshes/limo_wheel.dae" /> -->
            </geometry>
        </collision>
    </link>

    <link name="right_steering_hinge">
        <xacro:inertial_flip_cylinder mass="0.1" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_flip_cylinder>
    </link>
    <link name="left_steering_hinge">
        <xacro:inertial_flip_cylinder mass="0.1" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_flip_cylinder>
    </link>

    <!-- WHEEL JOINT -->

    <joint name="rear_left_wheel" type="continuous">
        <!-- <origin xyz="${-wheelbase/2} ${track/2} 0" rpy="${-pi/2} 0 0" /> -->
        <origin xyz="0 ${track/2} ${wheel_vertical_offset}" rpy="${-pi/2} 0 0" />
        <parent link="base_link" />
        <child link="rear_left_wheel_link" />
        <axis xyz="0 0 1" />
        <limit 
            effort="10.0" 
            lower="-3.14159265359" 
            upper="3.14159265359" 
            velocity="20.0"
            />
    </joint>

    <joint name="rear_right_wheel" type="continuous">
        <!-- <origin xyz="${-wheelbase/2} ${-track/2} 0" rpy="${-pi/2} 0 0" /> -->
        <origin xyz="0 ${-track/2} ${wheel_vertical_offset}" rpy="${-pi/2} 0 0" />
        <parent link="base_link" />
        <child link="rear_right_wheel_link" />
        <axis xyz="0 0 1" />
        <limit 
            effort="10.0" 
            lower="-3.14159265359" 
            upper="3.14159265359" 
            velocity="20.0"
            />
    </joint>

    <joint name="left_steering_hinge_wheel" type="revolute">
        <!-- <origin xyz="${wheelbase/2} ${track/2} 0" rpy="0 0 0" /> -->
        <origin xyz="${wheelbase} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="left_steering_hinge" />
        <axis xyz="0 0 1" />
        <limit 
            effort="10.00" 
            lower="-0.523598767" 
            upper="0.523598767" 
            velocity="10.00"/>
    </joint>

    <joint name="right_steering_hinge_wheel" type="revolute">
        <!-- <origin xyz="${wheelbase/2} ${-track/2} 0" rpy="0 0 0" /> -->
        <origin xyz="${wheelbase} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="right_steering_hinge" />
        <axis xyz="0 0 1" />
        <limit 
            effort="10.00" 
            lower="-0.523598767" 
            upper="0.523598767" 
            velocity="10.00"/>
    </joint>

    <joint name="front_left_wheel" type="continuous">
        <origin xyz="0 0 0" rpy="${-pi/2} 0 0" />
        <parent link="left_steering_hinge" />
        <child link="front_left_wheel_link" />
        <axis xyz="0 0 1" />
        <limit 
            effort="10.0" 
            lower="-3.14159265359" 
            upper="3.14159265359" 
            velocity="20.0"
            />
    </joint>

    <joint name="front_right_wheel" type="continuous">
        <origin xyz="0 0 0" rpy="${-pi/2} 0 0" />
        <parent link="right_steering_hinge" />
        <child link="front_right_wheel_link" />
        <axis xyz="0 0 1" />
        <limit 
            effort="10.0" 
            lower="-3.14159265359" 
            upper="3.14159265359" 
            velocity="20.0"
            />
    </joint>

</robot>